# Generated by Django 5.2.5 on 2025-08-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('service', models.CharField(choices=[('mental_health_counseling', 'Mental Health Counseling'), ('primary_care_consultation', 'Primary Care Consultation'), ('mobile_clinic_visit', 'Mobile Clinic Visit'), ('community_outreach', 'Community Outreach')], max_length=30)),
                ('preferred_date', models.DateField()),
                ('additional_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('agree_privacy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GetInvolvedInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('how_involved', models.CharField(choices=[('funder_donor', 'Funder/Donor'), ('volunteer', 'Volunteer'), ('organization_partner', 'Organization Partner'), ('fellowship_program', 'Fellowship Program'), ('brand_ally_csr', 'Brand Ally/CSR'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('health_updates', 'Health Updates'), ('community_stories', 'Community Stories'), ('education', 'Education'), ('technology', 'Technology'), ('partnerships', 'Partnerships')], max_length=20)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('read_time', models.IntegerField(help_text='In minutes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
