# Generated by Django 5.2.5 on 2026-03-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='annual_reports/')),
                ('report_file', models.FileField(upload_to='annual_reports/files/')),
                ('highlights', models.TextField(blank=True, help_text='Key highlights, one per line')),
                ('published_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
