# Generated by Django 5.2.5 on 2026-04-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_annualreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo embed URL')),
                ('caption', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, choices=[('community', 'Community'), ('clinic', 'Clinic'), ('events', 'Events'), ('team', 'Team'), ('outreach', 'Outreach')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
