# Generated by Django 5.2.5 on 2026-04-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_galleryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_hero_image', models.ImageField(blank=True, help_text='About page hero image', null=True, upload_to='site/')),
                ('home_hero_image', models.ImageField(blank=True, help_text='Home page hero image', null=True, upload_to='site/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
