# Generated by Django 5.2.5 on 2026-04-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(default='Monduli, Arusha, Tanzania', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_link',
            field=models.CharField(blank=True, default='/about/', help_text="URL for 'Learn more' link", max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_text',
            field=models.CharField(default='Primetel Health is now licensed as a medical clinic.', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='primetelhealth@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://www.instagram.com/primetel_health/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True, default='https://www.linkedin.com/company/primetel-health/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(default='+255 762 629 046', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_patients_treated',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_people_reached',
            field=models.PositiveIntegerField(default=45000),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_students_reached',
            field=models.PositiveIntegerField(default=15000),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_ussd_users',
            field=models.PositiveIntegerField(default=3600, help_text='e.g. 3600'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='website',
            field=models.CharField(default='health.primetel.tech', max_length=200),
        ),
    ]
