# Generated by Django 5.2.5 on 2026-04-09 04:01

from django.db import migrations, models


def seed_site_images(apps, schema_editor):
    SiteImage = apps.get_model("core", "SiteImage")
    keys = [
        "about_story_image",
        "about_team_emmanuel",
        "about_team_moshi",
        "about_team_elly",
        "about_team_kenneth",
        "about_team_albano",
        "about_team_rumas",
        "about_team_einoth",
        "services_primary_care",
        "services_mental_health",
        "services_outreach",
        "services_youth",
        "services_telehealth",
        "impact_partner_moh",
        "impact_partner_orkeeswa",
        "impact_partner_pfq",
    ]
    for key in keys:
        SiteImage.objects.get_or_create(key=key)


def unseed_site_images(apps, schema_editor):
    SiteImage = apps.get_model("core", "SiteImage")
    SiteImage.objects.filter(
        key__in=[
            "about_story_image",
            "about_team_emmanuel",
            "about_team_moshi",
            "about_team_elly",
            "about_team_kenneth",
            "about_team_albano",
            "about_team_rumas",
            "about_team_einoth",
            "services_primary_care",
            "services_mental_health",
            "services_outreach",
            "services_youth",
            "services_telehealth",
            "impact_partner_moh",
            "impact_partner_orkeeswa",
            "impact_partner_pfq",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_address_sitesettings_announcement_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('about_story_image', 'About: Story image'), ('about_team_emmanuel', 'About: Emmanuel team image'), ('about_team_moshi', 'About: Dr Epiphania Moshi team image'), ('about_team_elly', 'About: Dr Gy Elly Martin team image'), ('about_team_kenneth', 'About: Dr Keneth Masao team image'), ('about_team_albano', 'About: Albano Sabino team image'), ('about_team_rumas', 'About: Rumas team image'), ('about_team_einoth', 'About: Einoth Saitoti team image'), ('services_primary_care', 'Services: Primary healthcare image'), ('services_mental_health', 'Services: Mental health image'), ('services_outreach', 'Services: Community outreach image'), ('services_youth', 'Services: Youth and school health image'), ('services_telehealth', 'Services: Telehealth image'), ('impact_partner_moh', 'Impact: Ministry of Health logo'), ('impact_partner_orkeeswa', 'Impact: Orkeeswa logo'), ('impact_partner_pfq', 'Impact: Partners for Equity logo')], max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Upload a replacement image for this part of the site.', null=True, upload_to='site_images/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Image',
                'verbose_name_plural': 'Site Images',
                'ordering': ['key'],
            },
        ),
        migrations.RunPython(seed_site_images, unseed_site_images),
    ]
