# Generated by Django 5.2.5 on 2026-10-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_siteimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=50.0, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'USD ($)'), ('TZS', 'TZS (Tanzanian Shilling)')], default='USD', max_length=10)),
                ('frequency', models.CharField(choices=[('one_time', 'One-time gift'), ('monthly', 'Monthly sustaining support')], default='one_time', max_length=20)),
                ('allocation', models.CharField(choices=[('general', 'Where it is needed most (Urgent Care & Clinic Operations)'), ('mobile_clinic', 'Mobile Outreach Clinics & Rural Boma Visits'), ('mental_health', 'School Mental Health & Youth Workshops'), ('medication_fund', 'Patient Emergency Medication Fund'), ('telehealth', 'USSD *149*46# Telehealth Access')], default='general', max_length=30)),
                ('payment_preference', models.CharField(choices=[('mobile_money', 'Tanzania Mobile Money (M-Pesa / Tigo Pesa / Airtel Money)'), ('bank_transfer', 'Direct Bank Wire / Transfer'), ('card_pledge', 'Credit / Debit Card Pledge'), ('other', 'Other / Discuss with Primetel team')], default='mobile_money', max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Optional dedication or note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Donation Pledge',
                'verbose_name_plural': 'Donation Pledges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='key',
            field=models.CharField(choices=[('about_story_image', 'About: Story image'), ('about_team_emmanuel', 'About: Emmanuel team image'), ('about_team_moshi', 'About: Dr Epiphania Moshi team image'), ('about_team_elly', 'About: Dr Gy Elly Martin team image'), ('about_team_kenneth', 'About: Dr Keneth Masao team image'), ('about_team_albano', 'About: Albano Sabino team image'), ('about_team_rumas', 'About: Rumas team image'), ('about_team_einoth', 'About: Einoth Saitoti team image'), ('services_primary_care', 'Services: Primary healthcare image'), ('services_mental_health', 'Services: Mental health image'), ('services_outreach', 'Services: Community outreach image'), ('services_youth', 'Services: Youth and school health image'), ('services_telehealth', 'Services: Telehealth image'), ('impact_partner_moh', 'Impact: Ministry of Health logo'), ('impact_partner_orkeeswa', 'Impact: Orkeeswa logo'), ('impact_partner_pfq', 'Impact: Partners for Equity logo'), ('get_involved_funders', 'Get Involved: Funders / How You Can Help image'), ('get_involved_volunteers', 'Get Involved: Volunteers image'), ('get_involved_partners', 'Get Involved: Partners image'), ('get_involved_brand_ally', 'Get Involved: Brand Ally image')], max_length=100, unique=True),
        ),
    ]
