"""
Django settings for primetel_website project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import tempfile
import dj_database_url
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
IS_RENDER = bool(os.environ.get("RENDER"))
AZURE_SITE_ROOT = Path('/home/site')
RENDER_DISK_ROOT = Path('/var/data')
RENDER_TMP_ROOT = Path(tempfile.gettempdir()) / 'primetel_data'


def default_data_root():
    configured = os.environ.get('DATA_ROOT')
    if configured:
        return Path(configured)
    if AZURE_SITE_ROOT.exists():
        return AZURE_SITE_ROOT
    if IS_RENDER and RENDER_DISK_ROOT.exists():
        return RENDER_DISK_ROOT
    if IS_RENDER:
        return RENDER_TMP_ROOT
    return BASE_DIR


DATA_ROOT = default_data_root()


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=None):
    value = os.environ.get(name)
    if value is None:
        return default[:] if default else []
    return [item.strip() for item in value.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "dev-only-change-me-0f9c2a7e8b1346c5d412ef7a90b3c6d1a4e5f7b8c9d2e3a1",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", default=not IS_RENDER)

ALLOWED_HOSTS = env_list(
    "ALLOWED_HOSTS",
    default=[
        "127.0.0.1",
        "localhost",
        "primetel.onrender.com",
        "primetel-update-website.onrender.com",
        "health.primetel.tech",
    ],
)

CSRF_TRUSTED_ORIGINS = env_list(
    "CSRF_TRUSTED_ORIGINS",
    default=[
        "http://127.0.0.1:8000",
        "http://localhost:8000",
        "https://primetel.onrender.com",
        "https://primetel-update-website.onrender.com",
        "https://primetel-app-gch8e3gahfdhggfc.canadacentral-01.azurewebsites.net",
        "https://primetel.tech",
        "https://health.primetel.tech",
    ],
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'core',  # Your main app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'primetel_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.analytics_context',
                'core.context_processors.site_images_context',
                'core.context_processors.site_settings_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'primetel_website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=env_bool("DATABASE_SSL_REQUIRE", default=IS_RENDER),
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.environ.get('SQLITE_PATH', str(DATA_ROOT / 'db.sqlite3')),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Nairobi'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', str(DATA_ROOT / 'media')))
SERVE_MEDIA = env_bool("SERVE_MEDIA", default=True)
MEDIA_ROOT.mkdir(parents=True, exist_ok=True)

# --- Supabase Storage (S3-compatible) ---
# Set SUPABASE_URL, SUPABASE_S3_ACCESS_KEY, SUPABASE_S3_SECRET_KEY, and
# SUPABASE_BUCKET in the Render environment to activate cloud media storage.
_supabase_url = os.environ.get("SUPABASE_URL", "").rstrip("/")
_supabase_access_key = os.environ.get("SUPABASE_S3_ACCESS_KEY", "")
_supabase_secret_key = os.environ.get("SUPABASE_S3_SECRET_KEY", "")
_supabase_bucket = os.environ.get("SUPABASE_BUCKET", "media")

import logging as _logging
_storage_log = _logging.getLogger(__name__)
if _supabase_url and _supabase_access_key and _supabase_secret_key:
    _storage_log.warning("STORAGE: Supabase active — bucket=%s endpoint=%s/storage/v1/s3", _supabase_bucket, _supabase_url)
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
    AWS_ACCESS_KEY_ID = _supabase_access_key
    AWS_SECRET_ACCESS_KEY = _supabase_secret_key
    AWS_STORAGE_BUCKET_NAME = _supabase_bucket
    AWS_S3_ENDPOINT_URL = f"{_supabase_url}/storage/v1/s3"
    AWS_S3_REGION_NAME = os.environ.get("SUPABASE_REGION", "auto")
    AWS_S3_ADDRESSING_STYLE = "path"
    AWS_DEFAULT_ACL = "public-read"
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = False
    _supabase_host = _supabase_url.replace("https://", "")
    # django-storages uses AWS_S3_CUSTOM_DOMAIN to build file URLs, not MEDIA_URL.
    # Supabase public URL format: /storage/v1/object/public/<bucket>/<key>
    AWS_S3_CUSTOM_DOMAIN = f"{_supabase_host}/storage/v1/object/public/{_supabase_bucket}"
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"
else:
    _storage_log.warning(
        "STORAGE: Supabase INACTIVE — missing vars: %s",
        ", ".join(k for k, v in [
            ("SUPABASE_URL", _supabase_url),
            ("SUPABASE_S3_ACCESS_KEY", _supabase_access_key),
            ("SUPABASE_S3_SECRET_KEY", _supabase_secret_key),
        ] if not v)
    )

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

GA_MEASUREMENT_ID = os.environ.get("GA_MEASUREMENT_ID", "")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}

SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", default=not DEBUG)
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", default=not DEBUG)
SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "31536000" if not DEBUG else "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=not DEBUG)
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", default=not DEBUG)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
REFERRER_POLICY = "strict-origin-when-cross-origin"
